name: ecom_cycle
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/elecycle.png
    - asset/helmet.png
    - asset/mikkel-bech.png
    - asset/robert.png
    - asset/Road.png
    - asset/Mountain.png
    - asset/helmet-icon.png
    - asset/bicycle.png